In [1]:
%ls

 02_00_data_wrangling.ipynb
'A3_2 (1).ipynb'
'A3_Pivot Tables (1) (1).ipynb'
'A3_Pivot Tables (1).ipynb'
'A6_A00571517 (1).ipynb'
'A6_A00571517 (Error_Database).ipynb'
 A6_A00571517.ipynb
'A6_A00571517_Midterm Presentation.ipynb'
 adult.csv
 airline_data.csv
 antropometria00.csv
 antropometria-dataset.csv
 API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_3628907.csv
 Book3.csv
 Canada.xlsx
 Cartwheeldata.csv
 census.csv
 Class1
'Class2 (2).ipynb'
 Class2.ipynb
'Class_3 (1).ipynb'
'Class 4.ipynb'
'Class 5 (3).ipynb'
 coches.csv
 cwurData.csv
 data.csv
 datasets/
 headbrain.csv
 Metadata_Country_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_3628907.csv
 Metadata_Indicator_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_3628907.csv
 mic2.xlsx
 mic.xlsx
 movies.csv
 nhanes_2015_2016.csv
 pokemon.csv
 README.md
 reg_data.csv
 requirements.txt
 Reto/
 sample_pivot.csv
 tips.csv
 Untitled1.ipynb
 Untitled.ipynb
 weight-height.csv
 WorldBank.csv

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('reg_data.csv')
#df

In [7]:
pip install matplotlib

Requirement already satisfied: matplotlib in /srv/conda/envs/notebook/lib/python3.7/site-packages (3.2.1)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: numpy>=1.11 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (1.18.5)
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cycler>=0.10->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
     |████████████████████████████████| 292 kB 5.0 MB/s
Requirement already satisfied: numpy>=1.15 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.18.5)
Requirement already satisfied: pandas>=0.23 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.0.4)
Requirement already satisfied: scipy>=1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.4.1)
Requirement already satisfied: matplotlib>=2.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (3.2.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.23->seaborn) (2020.1)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.11.2
Note: you may need to restart the kernel to use updated packages.

In [10]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.13.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 6.2 MB/s
Collecting patsy>=0.5.2
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 54.2 MB/s
Requirement already satisfied: scipy>=1.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.4.1)
Requirement already satisfied: packaging>=21.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (21.3)
Requirement already satisfied: numpy>=1.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.18.5)
Requirement already satisfied: pandas>=0.25 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.0.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from packaging>=21.3->statsmodels) (2.4.7)
Requirement already satisfied: python-dateutil>=2.6.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2020.1)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-0.5.2 statsmodels-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [11]:
pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     |████████████████████████████████| 24.8 MB 5.9 MB/s
Requirement already satisfied: numpy>=1.14.6 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.18.5)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: scipy>=1.1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.4.1)
Collecting joblib>=0.11
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     |████████████████████████████████| 306 kB 58.0 MB/s
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=3c18c69a4ca0f39cd0ddb0b3f2fde1d90018374f433a6c71274bb5495b08e580
  Stored in directory: /home/jovyan/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn
Installing collected packages: threadpoolctl, joblib, scikit-learn, sklearn
Successfully installed joblib-1.1.0 scikit-learn-1.0.2 sklearn-0.0 threadpoolctl-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import numpy as np
from sklearn import linear_model

In [26]:
df.dropna(inplace = True)
df

    Gender  Salary   Age       Place  Weight Company Academic_degree
0   Female  1500.0  33.0     Chicago    80.0     BMW        Bachelor
1   Female  1200.0  33.0     Chicago    82.5    Ford              No
2     Male  2200.0  34.0    New York   100.8     BMW        Bachelor
3     Male  2100.0  42.0    New York    90.0     BMW          Master
4   Female  1500.0  29.0     Chicago    67.0    Ford          Master
5   Female  1700.0  42.0  Washington    60.0    Ford          Master
6     Male  3000.0  50.0  Washington    77.0    Ford              No
7     Male  3000.0  55.0  Washington    77.0    Ford        Bachelor
8   Female  2800.0  31.0    New York    87.0    Ford        Bachelor
9     Male  2900.0  46.0    New York    70.0      GM          Master
10  Female  2780.0  36.0  Washington    57.0     BMW              No
11    Male  2550.0  48.0    New York    64.0      GM          Master

1. Is there any effect of age on Salary? Use regression model to answer the question.

salary = b0 + b1*age

y = c + mx

y = df['Salary']
x = df['Age']

In [23]:
y = df['Salary']
x = df['Age']

type(x)

pandas.core.series.Series

In [28]:
y = pd.DataFrame(df['Salary'])
x = pd.DataFrame(df['Age'])

In [29]:
lm = linear_model.LinearRegression()

model_lm = lm.fit(x,y)
model_lm

LinearRegression()

In [31]:
print('The y intercept, b0 is = ', model_lm.intercept_)
print('The coefficient, b1 is = ', model_lm.coef_)
print('The R^2 is = ', model_lm.score(x,y))

The y intercept, b0 is =  [349.44580104]
The coefficient, b1 is =  [[48.09321584]]
The R^2 is =  0.380484541757693

# Salary = 349.44580104 + 48.09321584 * Age

Salary does not only depend on age.

In [ ]:
modelA = sm.OLS.from_formula('Salary ~ Age', data = df)